# Generated by Django 5.0.7 on 2024-09-24 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useruserpermissions',
            name='permission',
        ),
        migrations.RemoveField(
            model_name='useruserpermissions',
            name='user',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='user',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='user',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='workout',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='workout',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='usergoal',
            name='description',
            field=models.TextField(default='exit'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups'),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions'),
        ),
        migrations.AlterField(
            model_name='usergoal',
            name='goal',
            field=models.CharField(max_length=100),
        ),
        migrations.DeleteModel(
            name='UserGroups',
        ),
        migrations.DeleteModel(
            name='UserUserPermissions',
        ),
    ]
