# Generated by Django 5.0.7 on 2024-09-24 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_notification_created_at_notification_updated_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='video_url',
            field=models.URLField(default='exit'),
            preserve_default=False,
        ),
    ]
